
version: 2.1

jobs:
  build:
    parameters:
      python-version:
        type: string
      parallel-test:
        type: integer
        default: 2
    parallelism: <<parameters.parallel-test>>
    docker:
      - image: circleci/python:<<parameters.python-version>>
    steps:
      - checkout
      - restore_cache:
          key: dgc-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: dgc-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app

workflows:
  build-and-test:
    jobs:
      - build: 
          name: run-test-on-python-<<matrix.python-version >>
          matrix:
            parameters:
              python-version: ["3.7", "3.8", "3.9"]
          filters:
            branches:
              only: master
            